variables:
  artifacts: "bin/Release/netcoreapp3.1/publish"

resources:
  repositories:
    - repository: bedudeui # The name used to reference this repository in the checkout step
      type: github
      name: Dimss/bedudeui
      endpoint: Dimss

trigger:
  - master

jobs:
  
#  - job: build_bedudeui
#    pool:
#      vmImage: 'ubuntu-16.04'
#    steps:
#      - checkout: bedudeui
#      - task: Npm@1
#        inputs:
#          command: install
#      - task: Npm@1
#        inputs:
#          command: "custom"
#          customCommand: "run-script build"
#      - task: PublishBuildArtifacts@1
#        inputs:
#          pathToPublish: 'build'
#          artifactName: wwwroot
          

  - job: build_dotnet_core
#    dependsOn: "build_bedudeui"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
#      - task: DownloadBuildArtifacts@0
#        inputs:
#          artifactName: wwwroot
#          downloadPath: $(System.ArtifactsDirectory)
          
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
#          arguments: '-c Release --output $(artifacts) '
          arguments: '-c Release'

      - bash: "ls -all" 
          
#      - task: PublishBuildArtifacts@1
#        inputs:
#          pathToPublish: '$(artifacts)'
#          artifactName: api
