variables:
  artifacts: "bin/Release/netcoreapp3.1/publish"

resources:
  repositories:
    - repository: bedudeui # The name used to reference this repository in the checkout step
      type: github
      name: Dimss/bedudeui
      endpoint: Dimss

trigger:
  - master

jobs:

  - job: job1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: mkdir arts
      - bash: echo "artifact1" > arts/art1
      - bash: echo "artifact2" > arts/art2
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'arts'
  
  - job: job2
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: mkdir arts2
      - bash: echo "artifact1" > arts2/art1
      - bash: echo "artifact2" > arts2/art2
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'arts2'

#    - job: build_bedudeui
#      pool:
#        vmImage: 'ubuntu-16.04'
#      steps:
#        - checkout: bedudeui
#        - task: Npm@1
#          displayName: "Install deps"
#          inputs:
#            command: install
#        - task: Npm@1
#          displayName: "Build bundle"
#          inputs:
#            command: "custom"
#            customCommand: "run-script build"
#        - task: PublishBuildArtifacts@1
#          inputs:
#            pathToPublish: 'build'
#            artifactName: wwwroot
            


#  - job: build_dotnet_core
#    dependsOn: "build_bedudeui"
#    pool:
#      vmImage: 'ubuntu-16.04'
#    steps:
#      #      - task: DownloadBuildArtifacts@0
#      #        inputs:
#      #          artifactName: wwwroot
#      #          downloadPath: $(System.ArtifactsDirectory)
#
#      - task: DotNetCoreCLI@2
#        inputs:
#          command: 'publish'
#          arguments: '-c Release --output $(artifacts)'
#          zipAfterPublish: true
#          modifyOutputPath: false
#
#      - task: PublishBuildArtifacts@1
#        inputs:
#          pathToPublish: '$(artifacts)'
