variables:
  artifacts: "bin/Release/netcoreapp3.1/publish"

resources:
  repositories:
    - repository: bedudeui # The name used to reference this repository in the checkout step
      type: github
      name: Dimss/bedudeui
      endpoint: Dimss

trigger:
  - master

jobs:
  - job: build_bedudeui
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: bedudeui
      - task: Npm@1
        displayName: "Install deps"
        inputs:
          command: install
      - task: Npm@1
        displayName: "Build bundle"
        inputs:
          command: "custom"
          customCommand: "run-script build"
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: wwwroot
          pathToPublish: 'build'
  
      
  
  - job: build_dotnet_core
    dependsOn: "build_bedudeui"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: wwwroot
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          arguments: '-c Release --output $(artifacts)'
          zipAfterPublish: true
          modifyOutputPath: false

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(artifacts)'
