# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: build_dotnet_core
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: echo "DOTNET CORE BUILD"
  - job: build_reactjs
    pool:
      vmImage: 'ubuntu-16.04'
    dependsOn: build_dotnet_core 
    steps:
      - bash: echo "REACTJS BUILD"





#  - stage: B
#    jobs:
#      - job: B1
#        steps: 
#          - bash: echo "This is Job B1 at stage B"
#      - job: B2
#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
