# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  artifacts: "bin/Release/netcoreapp3.1/publish"

resources:
  repositories:
    - repository: bedudeui # The name used to reference this repository in the checkout step
      type: github
      name: Dimss/bedudeui
      endpoint: Dimss





trigger:
  - master

jobs:
  
  - job: build_bedudeui
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: bedudeui
      - task: Npm@1
        inputs:
          command: install
      - task: Npm@1
        inputs:
          command: custom
          customCommand: npm run-script build
          

  - job: build_dotnet_core
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          arguments: '-c Release --output $(artifacts) '
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(artifacts)'
          artifactName: drop
#  - job: build_reactjs
#    pool:
#      vmImage: 'ubuntu-16.04'
#    dependsOn: build_dotnet_core 
#    steps:
#      - bash: dotnet





#  - stage: B
#    jobs:
#      - job: B1
#        steps: 
#          - bash: echo "This is Job B1 at stage B"
#      - job: B2
#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
